### PR TITLE
Enhancements: enable "identify" command, add "-f" command-line option, remove duplicated codes

### PR DESCRIPTION
**Pull request by Ting-TT**
Enhancement of the functionalities of MLHub's OpenAI tool.

Changes include:
- Enable the "ml identify openai" command so the user can identify the language of the input audio.
- Add a command-line option "-f" so the user can specify the output format. Without specifying, the default output text is in one sentence per line now instead of a whole paragraph.
- The command-line option "-o" will save the result to an output file. And it will fail if the file already exists.
- A script is shared between both transcribe and translate to ensure the least duplicated codes.
- Update the README file.

### CODE REVIEW

**Review by gjwgit — DISMISSED** [review]
Testing

**Review by gjwgit — CHANGES_REQUESTED** [review]
Looks good. Tested. Thanks. Some suggestions:

- [x] `ml transcribe openai -o tmp.srt jokowi.wav` should generate `tmp.srt` in srt format. Currently it is txt.
- [x] -o tmp.json should output to a new file tmp.json in json format, for example, with the format determined by the filename extension.
- [x] -f without -o should output to stdout not write to a default file
- [x] there seems to be an extra blank line to stdout in the outputs
- [x] the file saved message should go to stderr rather than stdout so that `ml trascribe openai -o tmp.srt -f srt jokowi.wav 2> /dev/null` does not print anything to the console.
- [x] `-o tmp.srt` should fail if file already exists and write message to stderr to say file already exists
- [ ] have a non-0 return status if file already exists.

**Comment by gjwgit** [comment]
The IDENTIFY command works. But now I get failure on transcribe

```
06 Apr 21:28:52 gjw@kadesh ~/projects/openai$ ml identify openai harvard.wav
en,English
06 Apr 21:29:03 gjw@kadesh ~/projects/openai$ ml transcribe openai harvard.wav
/home/gjw/.local/lib/python3.11/site-packages/whisper/transcribe.py:115: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Traceback (most recent call last):
  File "/home/gjw/.local/lib/python3.11/site-packages/whisper/audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', 'harvard.wav', '-f', 's16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gjw/.local/lib/python3.11/site-packages/whisper/transcribe.py", line 478, in cli
    result = transcribe(model, audio_path, temperature=temperature, **args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gjw/.local/lib/python3.11/site-packages/whisper/transcribe.py", line 122, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gjw/.local/lib/python3.11/site-packages/whisper/audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "/home/gjw/.local/lib/python3.11/site-packages/whisper/audio.py", line 60, in load_audio
    raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
RuntimeError: Failed to load audio: ffmpeg version 6.0-6ubuntu1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-2ubuntu1)
  configuration: --prefix=/usr --extra-version=6ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
harvard.wav: No such file or directory

Skipping harvard.wav due to RuntimeError: Failed to load audio: ffmpeg version 6.0-6ubuntu1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Ubuntu 13.2.0-2ubuntu1)
  configuration: --prefix=/usr --extra-version=6ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
harvard.wav: No such file or directory

Command executed successfully!
```

**Comment by Ting-TT** [comment]
Thank you so much for providing the suggestions, Graham! 

All the`-f` and `-o` related suggestions are solved!

The only thing left is "having a non-0 return status if the file already exists", as we have discussed "sys.exit(1) for openai command will get lost through the mlhub command", and the return status of ml command is not affected by that sys.exit(1) currently.

**Comment by Ting-TT** [comment]
Added the following changes this week:
- Enable the command `ml supported openai` listed on [Survival Guide](https://survivor.togaware.com/mlhub/openai-supported.html)
- Return an error message immediately when unsupported format/language is given as the input

**Review by gjwgit — APPROVED** [review]

**Pull request merged**
